---
apiVersion: v1
kind: List
items:
-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: liferay
    labels:
      app: liferay
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
  spec:
    replicas: 1 
    selector:
      matchLabels:
        app: liferay
    strategy:
      type: RollingUpdate 
    template:
      metadata:
        labels:
          app: liferay
      spec:
        containers:
        - env: 
          - name: LIFERAY_JAVA_OPTS 
            value: -Xms2g -Xmx2g
          - name: LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE
            value: 0.0.0.0:11311
          - name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE 
            value: "true"
          - name: LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE 
            value: "domain"
          - name: JAVA_VERSION
            value: zulu11
          image: liferay:latest
          resources:
            requests: 
              memory: "2048Mi"
              cpu: "2"
            limits: 
              memory: "4098Mi"
              cpu: "3"
          name: liferay 
          ports: 
          - containerPort: 11311
          - containerPort: 8080
          readinessProbe: 
            httpGet:
              path: "/c/portal/layout"
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
          - mountPath: /opt/liferay/data
            name: liferay-data 
          - mountPath: /mnt/liferay
            name: liferay-config 
          # - mountPath: /opt/liferay/osgi/configs
          #   name: liferay-osgi-configs
          # - mountPath: /opt/liferay/osgi/marketplace
          #   name: liferay-osgi-marketplace
          # - mountPath: /opt/liferay/osgi/modules
          #   name: liferay-osgi-modules
          # - mouthPath: /opt/liferay/osgi/war
          #   name: liferay-osgi-war
        restartPolicy: Always 
        volumes: 
        - name: liferay-data
          emptyDir: {}
        - name: liferay-config
          emptyDir: {}
-
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: liferay
    name: liferay-svc
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP 
      targetPort: 8080
    selector:
      app: liferay
- 
  apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: liferay
  spec:
    to:
      kind: Service
      name: liferay-svc
    port:
      targetPort: 8080